### ISSUE TITLE
Code to reproduce benchmark in Figure 1?

### ISSUE THREAD

**Issue by neubig** [rycolab/paired-perm-test#1]
Thanks for this! This paper/method/code looks exciting.

Would it be possible to get an example of a script that can reproduce the benchmark numbers in figure 1? This would be very helpful to us to better understand the results.

**Comment by ranzmigrod** [comment]
Hi,

Thank you very much for your message. I've now pushed the script we used to run our runtime experiment. You can run the exact same experiment using
`python notes/runtime_experiment.py --output_file timers.pickle`
If you already ran it once and just want to reproduce the graph, add a `--graph_only` to the command line to avoid rerunning the whole experiment. I hope this is useful!

Note: we use [Aresnal](https://github.com/timvieira/arsenal) for timer capabilities.

**Comment by neubig** [comment]
Thanks so much! I'll take a look.
